# Databases
services:
  postgres:
    image: postgres:latest
    container_name: postgres_ecm_service
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_ecm_service
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=a4cb94a195540642a91be2e697da239a
    command: [ "redis-server", "--save", "20 1", "--requirepass", "a4cb94a195540642a91be2e697da239a" ]

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
